"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { calculateMeasurements, type Direction, type Opening } from "@/lib/calculations";

const labels:Record<Direction,string>={east:"東",west:"西",south:"南",north:"北"};
const directions=Object.keys(labels) as Direction[];
export default function MeasurementEditor({projectId,projectName}:{projectId:string;projectName:string}){const [method,setMethod]=useState<"RATE"|"OPENINGS">("RATE");const [walls,setWalls]=useState(Object.fromEntries(directions.map(d=>[d,{length:0,height:0,deductionRate:0}])) as Record<Direction,{length:number;height:number;deductionRate:number}>);const [openings,setOpenings]=useState<Opening[]>([]);const [roof,setRoof]=useState({leftRoofPlanArea:0,rightRoofPlanArea:0,leftRoofPitch:0,rightRoofPitch:0});const result=useMemo(()=>calculateMeasurements({walls,deductionMethod:method,openings,...roof}),[walls,method,openings,roof]);const update=(d:Direction,k:"length"|"height"|"deductionRate",v:string)=>setWalls(x=>({...x,[d]:{...x[d],[k]:Number(v)}}));return <><div className="topline"><div><h1>物件概要</h1><div className="hint">{projectName} ／ 自動値は緑、手入力値は黄で表示</div></div><Link className="button sub" href={`/projects/${projectId}`}>案件へ戻る</Link></div><div className="tabs">{["基本情報","建物寸法","外壁","屋根","足場","シーリング","付帯部","下地補修","集合住宅","その他"].map((x,i)=><button className={i===2?"active":""} key={x}>{x}</button>)}</div>
<div className="card" style={{marginBottom:16}}><h2>方角別 外壁</h2><div className="field" style={{maxWidth:300,marginBottom:16}}><label>開口部控除方法</label><select value={method} onChange={e=>setMethod(e.target.value as typeof method)}><option value="RATE">控除率方式</option><option value="OPENINGS">個別開口部方式</option></select></div><div className="table-wrap"><table><thead><tr><th>方角</th><th>長さ(m)</th><th>高さ(m)</th><th>総面積</th><th>控除率(%)</th><th>控除後面積</th></tr></thead><tbody>{directions.map(d=><tr key={d}><td><strong>{labels[d]}</strong></td><td><input className="cell-input manual" type="number" min="0" step="0.01" onChange={e=>update(d,"length",e.target.value)}/></td><td><input className="cell-input manual" type="number" min="0" step="0.01" onChange={e=>update(d,"height",e.target.value)}/></td><td className="money auto">{result.grossByDirection[d].toFixed(2)}</td><td><input disabled={method!=="RATE"} className="cell-input manual" type="number" min="0" max="100" onChange={e=>update(d,"deductionRate",e.target.value)}/></td><td className="money auto">{result.netByDirection[d].toFixed(2)}</td></tr>)}</tbody></table></div></div>
{method==="OPENINGS"&&<div className="card" style={{marginBottom:16}}><div className="topline"><h2>個別開口部</h2><button className="button" onClick={()=>setOpenings(x=>[...x,{direction:"east",width:0,height:0,quantity:1}])}>＋ 開口部</button></div>{openings.map((o,i)=><div className="grid three" key={i}><div className="field"><label>方角</label><select value={o.direction} onChange={e=>setOpenings(x=>x.map((v,n)=>n===i?{...v,direction:e.target.value as Direction}:v))}>{directions.map(d=><option value={d} key={d}>{labels[d]}</option>)}</select></div>{(["width","height","quantity"] as const).map(k=><div className="field" key={k}><label>{k==="width"?"幅":k==="height"?"高さ":"数量"}</label><input type="number" min="0" onChange={e=>setOpenings(x=>x.map((v,n)=>n===i?{...v,[k]:Number(e.target.value)}:v))}/></div>)}</div>)}</div>}
<div className="card"><h2>屋根（左右面の勾配を個別反映）</h2><div className="grid">{Object.entries({leftRoofPlanArea:"左屋根 投影面積",leftRoofPitch:"左屋根 勾配寸",rightRoofPlanArea:"右屋根 投影面積",rightRoofPitch:"右屋根 勾配寸"}).map(([k,l])=><div className="field" key={k}><label>{l}</label><input type="number" min="0" step="0.01" onChange={e=>setRoof(x=>({...x,[k]:Number(e.target.value)}))}/></div>)}</div></div><div className="summary"><span>外壁採用 <strong>{result.NET_WALL_AREA.toFixed(2)}㎡</strong></span><span>屋根 <strong>{result.ROOF_AREA.toFixed(2)}㎡</strong></span><span>外装合計 <strong>{result.EXTERIOR_TOTAL_AREA.toFixed(2)}㎡</strong></span></div></>}
