"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { calculateProperty, directions, type Direction, type PropertyOpening, type PropertyValues } from "@/lib/property-summary";

const dl: Record<Direction, string> = { east: "東", west: "西", south: "南", north: "北" };
const tabs = ["基本情報", "建物寸法", "外壁", "屋根", "足場", "シーリング", "付帯部", "下地補修", "集合住宅", "その他"] as const;
type Tab = typeof tabs[number];
type Field = { key: string; label: string; unit?: string; step?: string };
const accessoryFields: Field[] = [
  { key: "shutterBox", label: "シャッターボックス", unit: "m" }, { key: "partition", label: "パーテーション", unit: "㎡" }, { key: "canopy", label: "庇", unit: "㎡" },
  { key: "coping", label: "笠木", unit: "m" }, { key: "piping", label: "配管", unit: "m" }, { key: "handrail", label: "手摺", unit: "m" },
  { key: "flashing", label: "水切り", unit: "m" }, { key: "equipmentBase", label: "設備架台", unit: "箇所", step: "1" }, { key: "slimDuct", label: "スリムダクト", unit: "m" },
  { key: "steelPart", label: "鉄部", unit: "㎡" }, { key: "windowSill", label: "面台", unit: "m" }, { key: "steelDoor", label: "SD（鋼製建具）", unit: "箇所", step: "1" },
  { key: "equipmentStorageLarge", label: "設備収納庫 大", unit: "箇所", step: "1" }, { key: "equipmentStorageMedium", label: "設備収納庫 中", unit: "箇所", step: "1" }, { key: "equipmentStorageSmall", label: "設備収納庫 小", unit: "箇所", step: "1" },
  { key: "stormShutterLarge", label: "雨戸・戸袋 大", unit: "箇所", step: "1" }, { key: "stormShutterMedium", label: "雨戸・戸袋 中", unit: "箇所", step: "1" }, { key: "stormShutterSmall", label: "雨戸・戸袋 小", unit: "箇所", step: "1" },
  { key: "weatherCoverLarge", label: "ウェザーカバー 大", unit: "箇所", step: "1" }, { key: "weatherCoverMedium", label: "ウェザーカバー 中", unit: "箇所", step: "1" }, { key: "ventCap", label: "ベントキャップ", unit: "箇所", step: "1" },
  { key: "frameLarge", label: "枠 大", unit: "箇所", step: "1" }, { key: "frameMedium", label: "枠 中", unit: "箇所", step: "1" }, { key: "frameSmall", label: "枠 小", unit: "箇所", step: "1" },
  { key: "accessorySpare1", label: "予備欄1", unit: "式" }, { key: "accessorySpare2", label: "予備欄2", unit: "式" }, { key: "accessorySpare3", label: "予備欄3", unit: "式" },
];

function Num({ f, values, setValue }: { f: Field; values: PropertyValues; setValue: (key: string, value: number | string | boolean) => void }) { return <div className="field"><label>{f.label}{f.unit ? `（${f.unit}）` : ""}</label><input type="number" min="0" step={f.step ?? "0.01"} value={String(values[f.key] ?? "")} onChange={e => setValue(f.key, e.target.value === "" ? "" : Number(e.target.value))} /></div>; }
function Result({ label, value, unit }: { label: string; value: number; unit: string }) { return <div className="result-card"><span>{label}</span><strong>{value.toFixed(2)} {unit}</strong></div>; }
function Checks({ label, suffix, values, setValue }: { label: string; suffix: string; values: PropertyValues; setValue: (key: string, value: boolean) => void }) { return <div className="field"><label>{label}</label><div className="direction-checks">{directions.map(d => <label key={d}><input type="checkbox" checked={values[`${d}${suffix}`] === true} onChange={e => setValue(`${d}${suffix}`, e.target.checked)} /> {dl[d]}</label>)}</div></div>; }

export default function MeasurementEditor({ projectId, projectName, initialValues, initialOpenings }: { projectId: string; projectName: string; initialValues: PropertyValues; initialOpenings: PropertyOpening[] }) {
  const [tab, setTab] = useState<Tab>("建物寸法");
  const [values, setValues] = useState<PropertyValues>({ deductionMethod: "RATE", ...initialValues });
  const [openings, setOpenings] = useState(initialOpenings);
  const [state, setState] = useState<"idle" | "saving" | "saved" | "error">("idle");
  const [error, setError] = useState("");
  const c = useMemo(() => calculateProperty(values, openings), [values, openings]);
  const setValue = (key: string, value: number | string | boolean) => { setValues(v => ({ ...v, [key]: value })); setState("idle"); };
  const save = async () => { setState("saving"); setError(""); const response = await fetch(`/api/projects/${projectId}/measurements`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ values, openings }) }); const result = await response.json(); if (!response.ok) { setError(result.error ?? "保存に失敗しました。"); setState("error"); return; } setState("saved"); };
  const fields = (items: Field[], cls = "grid") => <div className={cls}>{items.map(f => <Num key={f.key} f={f} values={values} setValue={setValue} />)}</div>;

  return <><div className="topline"><div><h1>物件概要</h1><div className="hint">{projectName} ／ 入力値はSupabaseへ保存されます</div></div><div className="actions"><span className={state === "saved" ? "save-ok" : "hint"}>{state === "saving" ? "保存中…" : state === "saved" ? "保存しました" : "未保存"}</span><button className="button" disabled={state === "saving"} onClick={save}>保存</button><Link className="button sub" href={`/projects/${projectId}`}>案件へ戻る</Link></div></div>
  {error && <div className="error-box">{error}</div>}<div className="tabs">{tabs.map(x => <button type="button" className={tab === x ? "active" : ""} onClick={() => setTab(x)} key={x}>{x}</button>)}</div>

  {tab === "基本情報" && <section className="card"><h2>基本情報</h2><p>案件名・顧客名・住所・担当者は案件基本情報で一元管理します。</p><Link className="button sub" href={`/projects/${projectId}`}>案件基本情報へ</Link></section>}

  {tab === "建物寸法" && <section className="card"><h2>建物寸法</h2><p className="hint">方角別の外壁長さ・高さと軒の出を入力します。</p><div className="table-wrap"><table><thead><tr><th>方角</th><th>外壁長さ(m)</th><th>外壁高さ(m)</th><th>軒の出(m)</th><th>外壁面積(㎡)</th></tr></thead><tbody>{directions.map(d => <tr key={d}><td><strong>{dl[d]}</strong></td>{["WallLength", "WallHeight", "EaveLength"].map(k => <td key={k}><input className="cell-input manual" type="number" min="0" step="0.01" value={String(values[`${d}${k}`] ?? "")} onChange={e => setValue(`${d}${k}`, e.target.value === "" ? "" : Number(e.target.value))} /></td>)}<td className="money auto">{c.grossWallByDirection[d].toFixed(2)}</td></tr>)}</tbody></table></div>{fields([{ key: "foundationHeight", label: "基礎高さ", unit: "m" }, { key: "averageWallHeight", label: "平均外壁高さ", unit: "m" }], "grid section-gap")}</section>}

  {tab === "外壁" && <section className="card"><h2>外壁・開口部控除</h2><div className="field limit"><label>控除方法</label><select value={String(values.deductionMethod)} onChange={e => setValue("deductionMethod", e.target.value)}><option value="RATE">方角別の控除率</option><option value="OPENINGS">窓・ドアを個別登録</option></select></div>{values.deductionMethod === "RATE" ? <div className="table-wrap section-gap"><table><thead><tr><th>方角</th><th>総面積</th><th>控除率(%)</th><th>控除後面積</th></tr></thead><tbody>{directions.map(d => <tr key={d}><td>{dl[d]}</td><td className="money auto">{c.grossWallByDirection[d].toFixed(2)}</td><td><input className="cell-input manual" type="number" min="0" max="100" value={String(values[`${d}DeductionRate`] ?? "")} onChange={e => setValue(`${d}DeductionRate`, e.target.value === "" ? "" : Number(e.target.value))} /></td><td className="money auto">{c.netWallByDirection[d].toFixed(2)}</td></tr>)}</tbody></table></div> : <OpeningEditor openings={openings} setOpenings={setOpenings} />}</section>}

  {tab === "屋根" && <section className="card"><h2>屋根</h2><p className="hint">左右屋根面の投影面積と勾配寸を個別に反映します。</p>{fields([{ key: "leftRoofProjectedArea", label: "左屋根 投影面積", unit: "㎡" }, { key: "leftRoofPitch", label: "左屋根 勾配寸", unit: "寸" }, { key: "rightRoofProjectedArea", label: "右屋根 投影面積", unit: "㎡" }, { key: "rightRoofPitch", label: "右屋根 勾配寸", unit: "寸" }, { key: "roofDeductionRate", label: "屋根 開口控除率", unit: "%" }])}<div className="result-grid"><Result label="屋根総面積" value={c.GROSS_ROOF_AREA} unit="㎡" /><Result label="控除後屋根面積" value={c.ROOF_AREA} unit="㎡" /></div></section>}

  {tab === "足場" && <section className="card"><h2>足場</h2><p className="hint">Excelと同じく各面の外壁長さ＋隣接する軒の出＋0.2m、外壁高さ＋1mで計算します。</p><div className="table-wrap"><table><thead><tr><th>方角</th><th>自動足場面積(㎡)</th></tr></thead><tbody>{directions.map(d => <tr key={d}><td>{dl[d]}</td><td className="money auto">{c.scaffoldByDirection[d].toFixed(2)}</td></tr>)}</tbody></table></div><div className="result-grid"><Result label="足場面積 合計" value={c.SCAFFOLD_AREA} unit="㎡" /></div></section>}

  {tab === "シーリング" && <section className="card"><h2>シーリング</h2>{fields([{ key: "verticalJointCount", label: "縦目地 本数", unit: "本", step: "1" }, { key: "horizontalJointCount", label: "横目地 段数", unit: "段", step: "1" }, { key: "sashWidth", label: "サッシ回り平均長さ", unit: "m" }, { key: "sashQuantity", label: "サッシ数量", unit: "箇所", step: "1" }, { key: "balconySealingLength", label: "バルコニー等", unit: "m" }])}<div className="result-grid"><Result label="縦目地" value={c.VERTICAL_JOINT} unit="m" /><Result label="横目地" value={c.HORIZONTAL_JOINT} unit="m" /><Result label="合計" value={c.SEALING_LENGTH} unit="m" /></div></section>}

  {tab === "付帯部" && <section className="card"><h2>付帯部</h2><p className="hint">Excel「物件概要(2)」の付帯部項目をすべて入力できます。</p><h3>自動計算する付帯部</h3><div className="grid"><Checks label="破風を計上する方角" suffix="FasciaEnabled" values={values} setValue={setValue} /><Checks label="軒樋を計上する方角" suffix="GutterEnabled" values={values} setValue={setValue} /><Checks label="軒天を計上する方角" suffix="SoffitEnabled" values={values} setValue={setValue} /><Checks label="基礎を計上する方角" suffix="FoundationEnabled" values={values} setValue={setValue} /></div>{fields([{ key: "fasciaManual", label: "破風 追加長さ", unit: "m" }, { key: "eavesGutterManual", label: "軒樋 追加長さ", unit: "m" }, { key: "verticalGutterLength", label: "竪樋長さ", unit: "m" }, { key: "soffitManual", label: "軒天 追加面積", unit: "㎡" }, { key: "moldingLength", label: "幕板長さ", unit: "m" }, { key: "balconyArea", label: "バルコニー面積", unit: "㎡" }], "grid section-gap")}<div className="result-grid"><Result label="破風" value={c.FASCIA_LENGTH} unit="m" /><Result label="軒樋" value={c.EAVES_GUTTER_LENGTH} unit="m" /><Result label="竪樋" value={c.VERTICAL_GUTTER_LENGTH} unit="m" /><Result label="軒天" value={c.SOFFIT_AREA} unit="㎡" /><Result label="基礎" value={c.FOUNDATION_AREA} unit="㎡" /></div><h3 className="section-gap">その他の付帯部</h3>{fields(accessoryFields, "grid three")}<div className="field section-gap"><label>付帯部 備考</label><textarea rows={4} value={String(values.accessoryNotes ?? "")} onChange={e => setValue("accessoryNotes", e.target.value)} /></div></section>}

  {tab === "下地補修" && <section className="card"><h2>下地補修</h2>{fields([{ key: "crackUnder03", label: "クラック0.3mm未満", unit: "m" }, { key: "crackOver03", label: "クラック0.3～1.0mm", unit: "m" }, { key: "crackOver10", label: "クラック1.0mm超", unit: "m" }, { key: "missingUnder100", label: "欠損100×100未満", unit: "箇所" }, { key: "missingOver100", label: "欠損100×100以上", unit: "箇所" }, { key: "spallingUnder100", label: "爆裂100×100未満", unit: "箇所" }, { key: "spallingOver100", label: "爆裂100×100以上", unit: "箇所" }, { key: "weakArea", label: "脆弱部撤去", unit: "㎡" }, { key: "floatingArea", label: "浮き補修", unit: "㎡" }], "grid three")}</section>}

  {tab === "集合住宅" && <section className="card"><h2>集合住宅向け数量</h2>{fields([{ key: "corridorArea", label: "廊下面積", unit: "㎡" }, { key: "stairsArea", label: "階段面積", unit: "㎡" }, { key: "longSheetOtherArea", label: "長尺シート その他", unit: "㎡" }, { key: "corridorLength", label: "廊下長さ", unit: "m" }, { key: "corridorWidth", label: "廊下幅", unit: "m" }, { key: "stairFlights", label: "階段数", unit: "基" }, { key: "balconyCount", label: "バルコニー数", unit: "箇所" }])}<div className="result-grid"><Result label="長尺シート合計" value={c.LONG_SHEET_AREA} unit="㎡" /></div></section>}

  {tab === "その他" && <section className="card"><h2>その他数量</h2>{fields([{ key: "electricalWork", label: "電気工事", unit: "式" }, { key: "equipmentWork", label: "設備工事", unit: "式" }, { key: "temporaryWork", label: "仮設工事", unit: "式" }, { key: "environmentSafety", label: "環境安全費", unit: "式" }, { key: "machinery", label: "機械器具費", unit: "式" }, { key: "otherQuantity", label: "その他数量", unit: "式" }], "grid three")}<div className="field section-gap"><label>備考</label><textarea rows={5} value={String(values.measurementNotes ?? "")} onChange={e => setValue("measurementNotes", e.target.value)} /></div></section>}

  <div className="summary"><span>外壁 <strong>{c.NET_WALL_AREA.toFixed(2)}㎡</strong></span><span>屋根 <strong>{c.ROOF_AREA.toFixed(2)}㎡</strong></span><span>足場 <strong>{c.SCAFFOLD_AREA.toFixed(2)}㎡</strong></span><span>外装合計 <strong>{c.EXTERIOR_TOTAL_AREA.toFixed(2)}㎡</strong></span></div></>;
}

function OpeningEditor({ openings, setOpenings }: { openings: PropertyOpening[]; setOpenings: React.Dispatch<React.SetStateAction<PropertyOpening[]>> }) {
  const update = (i: number, key: keyof PropertyOpening, value: string | number) => setOpenings(rows => rows.map((r, n) => n === i ? { ...r, [key]: value } : r));
  return <div className="section-gap"><button type="button" className="button" onClick={() => setOpenings(rows => [...rows, { name: "", direction: "east", width: 0, height: 0, quantity: 1, notes: "" }])}>＋ 開口部</button><div className="table-wrap section-gap"><table><thead><tr><th>名称</th><th>方角</th><th>幅</th><th>高さ</th><th>数量</th><th>面積</th><th>備考</th><th></th></tr></thead><tbody>{openings.map((o, i) => <tr key={o.id ?? i}><td><input className="cell-input" value={o.name} onChange={e => update(i, "name", e.target.value)} /></td><td><select className="cell-input" value={o.direction} onChange={e => update(i, "direction", e.target.value)}>{directions.map(d => <option key={d} value={d}>{dl[d]}</option>)}</select></td>{(["width", "height", "quantity"] as const).map(k => <td key={k}><input className="cell-input" type="number" min="0" value={o[k]} onChange={e => update(i, k, Number(e.target.value))} /></td>)}<td className="money auto">{(o.width * o.height * o.quantity).toFixed(2)}</td><td><input className="cell-input" value={o.notes ?? ""} onChange={e => update(i, "notes", e.target.value)} /></td><td><button type="button" onClick={() => setOpenings(rows => rows.filter((_, n) => n !== i))}>×</button></td></tr>)}</tbody></table></div></div>;
}
